# Form implementation generated from reading ui file 'UI/ChangeEmailScene.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.current_mai_line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.current_mai_line.setGeometry(QtCore.QRect(430, 190, 113, 20))
        self.current_mai_line.setObjectName("current_mai_line")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 180, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(240, 290, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.new_mail_line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.new_mail_line.setGeometry(QtCore.QRect(430, 250, 113, 20))
        self.new_mail_line.setObjectName("new_mail_line")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(240, 240, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.cf_new_mail_line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.cf_new_mail_line.setGeometry(QtCore.QRect(430, 300, 113, 20))
        self.cf_new_mail_line.setObjectName("cf_new_mail_line")
        self.OK_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.OK_button.setGeometry(QtCore.QRect(290, 350, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.OK_button.setFont(font)
        self.OK_button.setObjectName("OK_button")
        self.cancel_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.cancel_button.setGeometry(QtCore.QRect(440, 350, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cancel_button.setFont(font)
        self.cancel_button.setObjectName("cancel_button")
        self.notice_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.notice_label.setGeometry(QtCore.QRect(40, 90, 721, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.notice_label.setFont(font)
        self.notice_label.setText("")
        self.notice_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.notice_label.setObjectName("notice_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Current email"))
        self.label_3.setText(_translate("MainWindow", "Confirm new email"))
        self.label_2.setText(_translate("MainWindow", "New email"))
        self.OK_button.setText(_translate("MainWindow", "OK"))
        self.cancel_button.setText(_translate("MainWindow", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
